register:
    path: /register
    controller: App\Controller\DefaultController::register
    methods: [POST]
    defaults:
        _format: json

api:
    path: /api
    controller: App\Controller\DefaultController::api
    defaults:
        _format: json

login_check:
    path:     /login_check
    methods:  [POST]
    defaults:
        _format: json

usersShow:
    path: /usersShow
    controller: App\Controller\UserController::usersShow
    methods:  [GET]
    defaults:
        _format: json

addConversation:
    path: /addConversation
    controller: App\Controller\ChatController::addConversation
    methods:  [POST]
    defaults:
        _format: json

addMessage:
    path: /addMessage
    controller: App\Controller\ChatController::addMessage
    methods:  [POST]
    defaults:
        _format: json
user:
    path: /user/{id}
    controller: App\Controller\UserController::user
    methods:  [Get]
    defaults:
        _format: json
